/**
 * What every jam starts with (plan slice 2): the starter library and the
 * starter parts. Pure data; imports nothing that touches audio, because jam
 * creation (Convex) upserts these by `starterKey`.
 *
 * The sounds are GENERATED by scripts/build-starters.mjs (Opus 5.5 through the
 * measured design loop, one WAV each) into starterSounds.ts. The parts are
 * hand-written: D minor, Dm Bb F C, one bar each, repeating.
 */

import type { DrumHit, DrumPattern, PitchedNote, PitchedPattern, PitchedRole } from "./pattern";
import type { ClaudioPreset } from "./preset";
import { STARTER_SOUND_DATA } from "./starterSounds";

export interface StarterSound {
  starterKey: string;
  name: string;
  /** The strip it's offered to. The producer can pick any pitched sound. */
  role: PitchedRole;
  /** Provenance for the library drawer: the WAV it was designed from. */
  source: string;
  rationale: string;
  designedWith: string;
  preset: ClaudioPreset;
}

export const STARTER_SOUNDS = STARTER_SOUND_DATA as unknown as readonly StarterSound[];

/** The sound each strip starts with, by starterKey. */
export const DEFAULT_SOUNDS = { bass: "bass-reso", keys: "keys-ep", you: "pad-square" } as const;

export function starterSound(key: string): StarterSound {
  const s = STARTER_SOUNDS.find((x) => x.starterKey === key);
  if (!s) throw new Error(`no starter sound ${key}`);
  return s;
}

const ORDER: readonly DrumHit["voice"][] = ["kick", "snare", "hat", "openhat"];

const hits = (voice: DrumHit["voice"], steps: number[], vel: number, accents: number[] = []): DrumHit[] =>
  steps.map((step) => ({ step, voice, vel, accent: accents.includes(step) }));

const note = (step: number, deg: number, len: number, vel: number, accent = false): PitchedNote => ({
  step,
  deg,
  len,
  vel,
  accent,
  tie: false,
});

/** Stored exactly as clampPattern would produce them (sorted, in range), so staging never rewrites them. */
export const STARTER_PARTS: { drums: DrumPattern; bass: PitchedPattern; keys: PitchedPattern } = {
  drums: {
    lengthBars: 1,
    notes: [
      ...hits("kick", [0], 0.95, [0]),
      ...hits("hat", [0, 2], 0.7),
      ...hits("snare", [4], 0.7),
      ...hits("hat", [4, 6], 0.7),
      ...hits("kick", [8], 0.95),
      ...hits("hat", [8], 0.7),
      ...hits("kick", [10], 0.95),
      ...hits("hat", [10], 0.7),
      ...hits("snare", [12], 0.7),
      ...hits("hat", [12], 0.7),
      ...hits("openhat", [14], 0.7),
    ].sort((a, b) => a.step - b.step || ORDER.indexOf(a.voice) - ORDER.indexOf(b.voice)),
  },
  bass: {
    lengthBars: 1,
    notes: [note(0, 0, 3, 0.75, true), note(6, 0, 2, 0.75), note(8, 0, 3, 0.75), note(14, 4, 2, 0.75)],
  },
  keys: {
    lengthBars: 1,
    notes: [0, 6, 12].flatMap((step) => [0, 2, 4].map((deg) => note(step, deg, step === 0 ? 3 : 2, 0.75))),
  },
};
