/**
 * GENERATED by scripts/build-starters.mjs — do not edit by hand; re-run it.
 * Starter sounds designed from WAVs with today's measured loop.
 */

export const STARTER_SOUND_DATA = [
  {
    "starterKey": "bass-reso",
    "name": "Monopoly Thump",
    "role": "bass",
    "source": "bass_monopoly_reso_thump.wav",
    "rationale": "A round, punchy 65 Hz FM bass with a hollow odd-harmonic core and a decaying thump — it gets the pitch, the attack, and the long decay of the sample. What's out of reach is the resonant filter peak sliding up through the harmonics and the grit of the original analog circuit; FM without feedback just sits too clean there.",
    "designedWith": "claude-opus-5-5",
    "preset": {
      "ampEnv": {
        "attack": 0.045,
        "decay": 0.95,
        "release": 0.81,
        "sustain": 0.25
      },
      "carrierFm": {
        "index": 1,
        "ratio": 2
      },
      "carrierWave": "sine",
      "detune": 0,
      "gain": 0.8,
      "harmonicity": 2,
      "modEnv": {
        "attack": 0.02,
        "decay": 0.5,
        "release": 1.2,
        "sustain": 0.35
      },
      "modulationIndex": 5,
      "modulatorFm": {
        "index": 0,
        "ratio": 3
      },
      "modulatorWave": "sine",
      "name": "Monopoly Thump"
    }
  },
  {
    "starterKey": "bass-sub",
    "name": "Juno Sub Round",
    "role": "bass",
    "source": "subbass_juno106.wav",
    "rationale": "A soft 65 Hz sine-sub with a slow swell and quick fade — it captures the Juno's register, gentle attack and near-pure low end. The sample's odd \"centroid climbing in the tail\" is just the sub dying into room noise, which FM can't reproduce; chasing it would only make the patch buzzy.",
    "designedWith": "claude-opus-5-5",
    "preset": {
      "ampEnv": {
        "attack": 0.37,
        "decay": 0.16,
        "release": 0.2,
        "sustain": 0.05
      },
      "carrierFm": {
        "index": 0,
        "ratio": 1
      },
      "carrierWave": "sine",
      "detune": 0,
      "gain": 0.8,
      "harmonicity": 2,
      "modEnv": {
        "attack": 0.6,
        "decay": 0.3,
        "release": 1,
        "sustain": 0.4
      },
      "modulationIndex": 1.4,
      "modulatorFm": {
        "index": 0,
        "ratio": 1
      },
      "modulatorWave": "sine",
      "name": "Juno Sub Round"
    }
  },
  {
    "starterKey": "keys-ep",
    "name": "Velvet Tine EP",
    "role": "keys",
    "source": "electric_piano_jd800_soft_ep.wav",
    "rationale": "A soft struck-tine electric piano: quick strike, slightly inharmonic metallic shimmer around the 5th partial, brightness mellowing as it decays. The JD-800's sampled grit and its very bright, airy tail are beyond a 4-op patch, so I kept the register, attack and decay honest and let the timbre stay silkier than the original.",
    "designedWith": "claude-opus-5-5",
    "preset": {
      "ampEnv": {
        "attack": 0.015,
        "decay": 1.23,
        "release": 0.6,
        "sustain": 0.12
      },
      "carrierFm": {
        "index": 2,
        "ratio": 3.47
      },
      "carrierWave": "sine",
      "detune": 0,
      "gain": 0.8,
      "harmonicity": 5.01,
      "modEnv": {
        "attack": 0.02,
        "decay": 1.2,
        "release": 1.5,
        "sustain": 0.35
      },
      "modulationIndex": 11,
      "modulatorFm": {
        "index": 2,
        "ratio": 1.41
      },
      "modulatorWave": "sawtooth",
      "name": "Velvet Tine EP"
    }
  },
  {
    "starterKey": "keys-organ",
    "name": "Drawbar Glass",
    "role": "keys",
    "source": "organ_jd800_organish.wav",
    "rationale": "A clean drawbar-style FM organ: instant attack, steady sustain, octave colour from the inner operator at ratio 4. The sample's exact octave-stack harmonic recipe (loud 4th and 8th partials with quiet neighbours) is really additive drawbars, which FM can only approximate — mine is a touch darker and smoother than the JD-800.",
    "designedWith": "claude-opus-5-5",
    "preset": {
      "ampEnv": {
        "attack": 0.004,
        "decay": 3.8,
        "release": 0.14,
        "sustain": 0.35
      },
      "carrierFm": {
        "index": 1.2,
        "ratio": 4
      },
      "carrierWave": "sine",
      "detune": 2,
      "gain": 0.8,
      "harmonicity": 1,
      "modEnv": {
        "attack": 0.02,
        "decay": 1.5,
        "release": 0.14,
        "sustain": 0.8
      },
      "modulationIndex": 4,
      "modulatorFm": {
        "index": 0,
        "ratio": 2
      },
      "modulatorWave": "sine",
      "name": "Drawbar Glass"
    }
  },
  {
    "starterKey": "pad-square",
    "name": "Fat Square Pad",
    "role": "keys",
    "source": "pad_jd800_fat_square.wav",
    "rationale": "A slow-swelling odd-harmonic square pad: same register, same 350 ms bloom, same long sustained body as the JD-800 patch. The sample's chorused analog stack and its very high, slightly shifting sustain brightness are beyond a single FM voice, so this is the coherent-instrument version of it rather than a clone.",
    "designedWith": "claude-opus-5-5",
    "preset": {
      "ampEnv": {
        "attack": 0.35,
        "decay": 4,
        "release": 0.888,
        "sustain": 0.8
      },
      "carrierFm": {
        "index": 0,
        "ratio": 2
      },
      "carrierWave": "square",
      "detune": 6,
      "gain": 0.8,
      "harmonicity": 2,
      "modEnv": {
        "attack": 0.5,
        "decay": 1.2,
        "release": 0.888,
        "sustain": 0.55
      },
      "modulationIndex": 6,
      "modulatorFm": {
        "index": 0,
        "ratio": 2
      },
      "modulatorWave": "square",
      "name": "Fat Square Pad"
    }
  }
];
